### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by rojinsafavi** [nanoporetech/currennt#3]
Is Currennt compatible with Mac? I couldn't find installation steps for Mac.

**Comment by cjw85** [comment]
Hi,

I haven't personally tried compiling currennt on OSX: I've had no use for it since I don't have a Mac with an Nvidia GPU. You might like to try searching the original sourceforge site for help.

**Comment by clive-g-brown** [comment]
I have had currennt working on mac, and we posted an opencl version of it somewhere sometime back.

Sent from my iPad

On 11 Feb 2017, at 19:16, cjw85 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I haven't personally tried compiling currennt on OSX: I've had no use for it since I don't have a Mac with an Nvidia GPU. You might like to try searching the original sourceforge site for help.

**Comment by rojinsafavi** [comment]
Could you please me the address to where it was posted?
