### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by rojinsafavi** [nanoporetech/currennt#4]
When I follow the following steps on our linux server( I do not have root access):

#> cd currennt
#> mkdir build && cd build
#> cmake ..
#> make

I get at error at make step:

/soe/rojinsafavi/anaconda2/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libnetcdf.so: undefined reference to `H5Tget_member_type'
/soe/rojinsafavi/anaconda2/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libnetcdf.so: undefined reference to `H5Fget_obj_count'
/soe/rojinsafavi/anaconda2/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libnetcdf.so: undefined reference to `H5Gget_objinfo'
/soe/rojinsafavi/anaconda2/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libnetcdf.so: undefined reference to `SDgetfillvalue'
collect2: error: ld returned 1 exit status
make[2]: *** [currennt] Error 1
make[1]: *** [CMakeFiles/currennt.dir/all] Error 2
make: *** [all] Error 2
[rojinsafavi@citrisdance build]$

and if I execute make in the ~/currennt directory instead of building directory I get this:

/usr/bin/ld: cannot open output file currennt: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [currennt] Error 1
make[1]: *** [CMakeFiles/currennt.dir/all] Error 2
make: *** [all] Error 2

I was wondering if I can get some help.

Thanks!

**Comment by cjw85** [comment]
This looks like your system does not have the HDF header files installed. You can ask your system administrator to install the HDF development and library packages. For Debian based Linuxes see the Makefile in the repository, which your system administrator could use to build a package to install.

**Comment by rojinsafavi** [comment]
If I execute make in the ~/currennt directory instead of building directory I get this: (not sure if this is correct though)

/usr/bin/ld: cannot open output file currennt: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [currennt] Error 1
make[1]: *** [CMakeFiles/currennt.dir/all] Error 2
make: *** [all] Error 2

**Comment by cjw85** [comment]
You will not be able to execute make in the top-level directory if you cannot run cmake in a build sub-directory, since the first stage of the Makefile is to run the cmake build.

I would suggest asking your system administrator (or someone otherwise knowledgeable in compiling packages from source) for help obtaining and installing the build dependencies.

We provide a prebuilt binary for Ubuntu14 at the link below which will short-circuit the build process. Your system administrator will be able to install this for you.

https://github.com/nanoporetech/currennt/releases

Before continuing I would ensure, if you have not already, that you have a working CUDA environment as efficient use of currennt is contingent on this.

**Comment by rojinsafavi** [comment]
I managed to solve the issue, I'm not getting any error anymore.

Thanks,
Rojin
